#!/user/bin/env python

from big_ol_pile_of_manim_imports import *
import numpy as np
        
class Formula2(Scene):

    def construct(self):

        int_text = TexMobject("Whole Number")
        dec_text = TexMobject("Decimal")
        fra_text = TexMobject("Fraction")

        integer = TexMobject("1")
        decimal = TexMobject("0.5")
        fraction = TexMobject(r"1", r"\over", r"2").set_color_by_tex("2", RED)

        dec_to_frac = TexMobject(r"1", r"\over", r"2").set_color_by_tex("1", GREEN)

        numerator = TexMobject("Numerator").set_color(GREEN)
        denominator = TexMobject("Denominator").set_color(RED)

        question1 = TextMobject("How Many 2's Fit Into 1?")
        answer1 = TextMobject("NONE... right?")
        text1 = TextMobject("Yes! No Whole 2's Fit Into 1 as a WholeNumber")
        text2 = TextMobject("Although parts of 2 can... How?")
        text3 = TextMobject("Which Is In The Same Meaning As")
        text4 = TextMobject("So What Is The Answer To Such Question?")
        text5 = TextMobject("But Why?")
        text6 = TextMobject("Exactly 50 Percent Of 2 Fits Into 1")
        text7 = TextMobject("Which Is Why The Fraction")
        text8 = TextMobject("Is Equivalent To 0.5 or 50 Percent")

        numerator_int = TexMobject("1").set_color(GREEN)
        denominator_int = TexMobject("2").set_color(RED)

        equation1 = TexMobject(r"\frac { 2 }{ 1 } \quad =\quad 2")
        equation2 = TexMobject(r"2\quad divide\quad 1\quad =\quad 2")
        equation3 = TexMobject(r"1\quad divide\quad 2\quad =\quad ?")
        equation3_1 = TexMobject(r"1\quad divide\quad 2\quad =\quad 0.5")
        
        integer.scale(2)
        decimal.scale(2)
        fraction.scale(2)
        dec_to_frac.scale(2)
        numerator_int.scale(2)
        denominator_int.scale(2)
        equation1.scale(2)
        equation2.scale(2)
        equation3.scale(2)
        equation3_1.scale(2)


        self.play(Write(int_text), run_time=3)
        self.wait(2)
        self.play(int_text.shift, 1*UP)
        self.wait(3)
        self.play(Write(integer), run_time=3)
        self.wait(5)
        self.play(integer.shift, 5*LEFT)
        self.play(int_text.shift, 5*LEFT)
        self.wait(3)

        self.play(Write(dec_text), run_time=3)
        self.wait(2)
        self.play(dec_text.shift, 1*UP)
        self.wait(3)
        self.play(Write(decimal), run_time=3)
        self.wait(5)
        self.play(decimal.shift, 5*RIGHT)
        self.play(dec_text.shift, 5*RIGHT)
        self.wait(3)

        self.play(Write(fra_text), run_time=3)
        self.wait(2)
        self.play(fra_text.shift, 1.5*UP)
        self.wait(3)
        self.play(Write(fraction), run_time=3)
        self.wait(5)

        self.play(FadeOut(int_text))
        self.play(FadeOut(integer))
        self.wait(1)
        self.play(fra_text.shift, 2*LEFT)
        self.play(fraction.shift, 2*LEFT)
        self.wait(2)
        self.play(dec_text.shift, 2*LEFT)
        self.play(decimal.shift, 2*LEFT)
        self.wait(3)
        self.play(FadeOut(dec_text))
        self.play(FadeOut(fra_text))
        self.wait(1)
        self.play(ReplacementTransform(decimal, dec_to_frac))
        self.play(dec_to_frac.shift, 2*RIGHT)
        self.play(fraction.shift, 0.5*RIGHT)
        self.wait(2)

        self.play(Write(numerator), run_time=2)
        self.play(numerator.shift, 0.5*UP)
        self.play(numerator.shift, 4*RIGHT)
        self.wait(1)
        self.play(Write(denominator), run_time=2)
        self.play(denominator.shift, 0.5*DOWN)
        self.play(denominator.shift, 4*LEFT)
        self.wait(3)
        self.play(FadeOutAndShift(fraction))
        self.play(FadeOutAndShift(dec_to_frac))
        self.wait(1)
        self.play(numerator.shift, 4*LEFT)
        self.play(denominator.shift, 4*RIGHT)
        self.wait(3)

        self.play(numerator.shift, 2*UP)
        self.play(denominator.shift, 2*DOWN)
        self.wait(1)

        self.play(ReplacementTransform(numerator, numerator_int))
        self.play(numerator_int.shift, 2*UP)
        self.wait(1)
        self.play(ReplacementTransform(denominator, denominator_int))
        self.play(denominator_int.shift, 2*DOWN)
        self.wait(1)
        self.play(Write(question1), run_time=3)
        self.wait(2)
        self.play(FadeOutAndShiftDown(numerator_int), FadeOutAndShift(denominator_int))
        self.play(question1.shift, 3*UP)
        self.wait(1)
        self.play(Write(answer1), run_time=3)
        self.play(FadeOut(question1))
        self.play(answer1.shift, 3*UP)
        self.wait(1)
        self.play(Write(text1), run_time=3)
        self.wait(2)
        self.play(FadeOutAndShift(answer1), direction=UP)
        self.play(text1.shift, 3*UP)
        self.play(Write(text2), run_time=3)
        self.wait(2)
        self.play(FadeOutAndShift(text1), direction=UP)
        self.play(ReplacementTransform(text2, equation1))
        self.wait(2)
        self.play(FadeInFrom(text3), direction=UP)
        self.play(text3.shift, 2*UP)
        self.wait(1)
        self.play(ReplacementTransform(equation1, equation2))
        self.wait(3)
        self.play(ReplacementTransform(text3, text4))
        self.play(text4.shift, 1.5*UP)
        self.play(ReplacementTransform(equation2, equation3))
        self.wait(1)
        self.play(ReplacementTransform(equation3, equation3_1))
        self.wait(1)
        self.play(ReplacementTransform(text4, text5))
        self.play(text5.shift, 1.5*UP)
        self.wait(3)
        self.play(ReplacementTransform(equation3_1, text6))
        self.wait(2)
        self.play(FadeOutAndShift(text5), direction=UP)
        self.play(text6.shift, 1.5*UP)
        self.play(FadeOutAndShift(text6), direction=UP)
        self.play(Write(text7), run_time=2)
        self.play(text7.shift, 2*UP)
        self.play(text7.shift, 3*LEFT)
        self.play(Write(fraction), run_time=3)
        self.wait(1)
        self.play(Write(text8), run_time=2)
        self.play(text8.shift, 2*DOWN)
        self.play(text8.shift, 3*RIGHT)
        self.wait(5)
        self.play(FadeOutAndShift(text7), direction=RIGHT)
        self.play(FadeOutAndShift(fraction), direction=DOWN)
        self.play(FadeOutAndShift(text8), direction=LEFT)
        self.wait(2)



        

        

